# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='area',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
