# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_subject_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='subject',
            name='sem_offered',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='sem_taken',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
