# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20160314_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sem_offered',
        ),
    ]
